// project/micro-app-demo/vue2-child/src/views/CommunicationTest.vue
<template>
  <a-space direction="vertical" class="box" :size="40">
    <a-divider class="title">
      <h1>Vue2子应用页面</h1>
    </a-divider>
    <user-info></user-info>
    <a-divider class="title">
      <h2>Vue2子应用向主应用通信</h2>
    </a-divider>
    <message-trigger />
    <a-divider class="title">
      <h2>Vue2子应用Counter</h2>
    </a-divider>
    <counter />
  </a-space>
</template>

<script lang="ts">
import { Divider, Space } from 'ant-design-vue'
import UserInfo from '@/components/UserInfo.vue'
import Counter from '@/components/Counter.vue'
import MessageTrigger from '@/components/MessageTrigger.vue'

export default {
  name: 'User',
  components: {
    MessageTrigger,
    Counter,
    UserInfo,
    [Divider.name]: Divider,
    [Space.name]: Space
  }
}
</script>

<style scoped lang="less">
.box {
  width: 100%;
}

h1 {
  font-size: 2em;
  margin-bottom: 0;
}

h2 {
  margin-bottom: 0;
}
</style>

// project/icestark-demo/vite-child/src/views/CommunicationTest/index.tsx
import { Divider, Space, Typography } from 'antd'
import UserInfo from '@/components/UserInfo'
import MessageTrigger from '@/components/MessageTrigger'
import Counter from '@/components/Counter'

export default function CommunicationTest() {
  return (
    <>
      <Space size={40} direction="vertical" style={{ width: '100%'}}>
        <Divider>
          <Typography.Title>Vite子应用页面</Typography.Title>
        </Divider>
        <UserInfo />
        <Divider>
          <Typography.Title level={2}>Vite子应用向主应用通信</Typography.Title>
        </Divider>
        <MessageTrigger />
        <Divider>
          <Typography.Title level={2}>Vite子应用Counter</Typography.Title>
        </Divider>
        <Counter />
      </Space>
    </>
  )
}
